# taps
tap "koekeishiya/formulae"

# formulae
brew "coreutils"
brew "ripgrep"
brew "fd"
brew "eza"
brew "zoxide"
brew "bat"
brew "mise"
brew "jq"
brew "stow"
brew "tree-sitter"
brew "rust-analyzer"
brew "clang-format"
brew "cmake"
brew "lazygit"
brew "neovim"
brew "node"
brew "atuin"
brew "btop"
brew "fzf"
brew "aria2"
brew "yt-dlp"
brew "ranger"
brew "docker"
brew "colima"
brew "koekeishiya/formulae/yabai"
brew "koekeishiya/formulae/skhd"
brew "just"

# casks
cask "alacritty"
# cask "shortcat"
cask "font-jetbrains-mono-nerd-font"
cask "qlmarkdown"
cask "karabiner-elements"
