quitOnTopLevelReturn: true
promptToReturnFromSubprocess: false

os:
    editPreset: 'nvim'

customCommands:
    - key: 'x'
      context: 'global'
      command: 'open . -a Xcode'
      subprocess: false
      description: 'Open branch in Xcode'
    - key: '<c-x>'
      context: 'files'
      command: 'open {{ .SelectedFile.Name }} -a Xcode'
      subprocess: false
      description: "Open file in Xcode"

gui:
    screenMode: 'normal'
    theme:
      activeBorderColor:
        - '#e78284'
        - bold
      inactiveBorderColor:
        - '#a5adce'
      optionsTextColor:
        - '#8caaee'
      selectedLineBgColor:
        - '#414559'
      cherryPickedCommitBgColor:
        - '#51576d'
      cherryPickedCommitFgColor:
        - '#e78284'
      unstagedChangesColor:
        - '#e78284'
      defaultFgColor:
        - '#c6d0f5'
      searchingActiveBorderColor:
        - '#e5c890'
    authorColors:
      '*': '#babbf1'
