gui:
    screenMode: 'normal'
os:
    editPreset: 'nvim'
promptToReturnFromSubprocess: false
customCommands:
    - key: 'x'
      context: 'global'
      command: 'open *.xcwo*'
      subprocess: false
