[general]
import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"alacr
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
title = "A-la-critty"
[font]
normal = { family = "Victor Mono", style = "Regular" }
size = 20
