[general]
import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
# alternatives:
# FiraCode Nerd Font Mono
# Victor Mono
# IosevkaTerm Nerd Font Mono
# JetBrainsMono Nerd Font Mono
normal = { family = "JetBrainsMono Nerd Font Mono", style = "ExtraLight" }
size = 18

[keyboard]
bindings = [
  # alt + right to go forward by word
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  # alt + left to go back by word
  { key = "Left", mods = "Alt", chars = "\u001BB" },
]
