[general]
import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"alacr
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
# alternatives:
# FiraCode Nerd Font Mono
# Victor Mono
# IosevkaTerm Nerd Font Mono
# JetBrainsMono Nerd Font Mono
normal = { family = "JetBrainsMono Nerd Font Mono", style = "ExtraLight" }
size = 24
